apiVersion: v2
name: nginx-dev
description: A Helm chart for NGINX in the development environment
version: 1.0.0
appVersion: "1.19.6"
dependencies:
  - name: nginx
    version: 1.0.0
    repository: "file://../../common-charts/nginx"