apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dev
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:1.21.0
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-dev-service
spec:
  type: NodePort